### ISSUE TITLE
[CASINOS LISTED ON SOME DEVICES / ACCOUNTS AND NOT ON OTHERS]

### ISSUE THREAD

**Issue by georgemac70cr8** [asgiom/cr8-brm-mobile-issues#16]
**Describe the bug**
2 people - matt and george - matt sees list of casinos, george doesn't.

1. Go to 'home'
2. Look under "Casinos"

**Expected behavior**
George should see the same as Matt - a list of participating casinos

**Screenshots**
ATTACHED - matt's and george's to compare
![photo_2020-08-19 12 46 45](https://user-images.githubusercontent.com/69824025/90625577-17876e00-e21a-11ea-970e-fd34ff7de640.jpeg)
![photo_2020-08-19 12 36 44](https://user-images.githubusercontent.com/69824025/90625583-19e9c800-e21a-11ea-84a8-62d43c2cacfa.jpeg)

**Smartphone (please complete the following information):**
huawei p20 pro
samsung galaxy s9

**Additional context**

**Comment by t3nshi** [comment]
Have you allowed the app to provide location? casinos are showed related to user location. If you don't enable location or don't give permission to app to access location that could explain your casinos not showing

**Comment by georgemac70cr8** [comment]
yes, i always allow everything

**Comment by t3nshi** [comment]
So your answer leaves the impression that you allowed the permission to location... but can you explicitly confirm that when you open the app with location service (GPS) ON the app don't show any casino?

**Comment by georgemac70cr8** [comment]
here's a screen recording showing that i allowed all [premissions...](https://vimeo.com/449290280)
 and screenshot of my location settings with cr8 in the list of apps...

![Screenshot_20200819_160827_com google android permissioncontroller](https://user-images.githubusercontent.com/69824025/90645668-87a3ed00-e236-11ea-8ca5-36f5c977d3b4.jpg)

**Comment by t3nshi** [comment]
We already cleared that. I asked for a very different thing. Can you please check if you have GPS enabled or disabled? and try to ENABLE GPS and then open the app and see if the casinos shows or not? let's open for example google maps, and make sure the map shows your location... 
I am just checking that your issue is a bug or figuring out if it is an intended behaviour.

**Comment by georgemac70cr8** [comment]
yes, maps works showing my location. attached screenshot of googlemaps shows my location right now. i always have gps enabled by default but i don't know excatly what i need to show you in my phone settings. see screenshots.

![Screenshot_20200819_164315_com android settings](https://user-images.githubusercontent.com/69824025/90649741-57ab1880-e23b-11ea-8dfb-9b9fbb4b8594.jpg)

![Screenshot_20200819_163927_com google android apps maps](https://user-images.githubusercontent.com/69824025/90649753-5a0d7280-e23b-11ea-9b32-e39415a943da.jpg)

**Comment by danielwwf** [comment]
We need a prompt telling the user that GPS is disabled and is MANDATORY to use the app for geofencing. It should then take them to their setting to enable GPS. Lot's of other apps do this.

**Comment by t3nshi** [comment]
Yes you're right. We did talked about that yesterday and we should implement it. I will update once we have this. By the way, is strange what is happening here since if the location is in  Malta he should see the 2 casinos since those casinos are enabled for all countries.

**Comment by danielwwf** [comment]
Recovered George acc on my device, I get a list. The issue seems to be related to Huawei devices and not getting location data properly.

**Comment by danielwwf** [comment]
Confirmed on a second Huawei, its a device issue

**Comment by t3nshi** [comment]
Right now @ajochems disabled the geofencing as requested here #41 , while we find how to circumvent some huawei restrictions. So I will put this on hold

**Comment by danielwwf** [comment]
This should have been fixed with us disabling geofencing, which worked for most devices (Huawei) but NOT Samsung. Here is an output of the debugging Samsung Note 8, Droid 10

![image](https://user-images.githubusercontent.com/30388756/91721851-b5275980-eb99-11ea-9e27-a6ff173ecea0.png)

**Comment by t3nshi** [comment]
> This should have been fixed with us disabling geofencing, which worked for most devices (Huawei) but NOT Samsung

I didn't understand what you just wrote here... So you say that disabling geofencing didn't work for Samsung? am I understanding correctly? Or you meant something else? And let me tray to clear that out, you mean that with the geofencing disabled the Samsung still don't get any casinos?

**Comment by danielwwf** [comment]
> Right now @ajochems disabled the geofencing as requested here #41 , while we find how to circumvent some Huawei restrictions. So I will put this on hold

The issue is **NOT** fixed on **Samsung** devices. If GPS is disabled on the device, no casinos are shown. Confirmed on S9, S9+, Note8, and Note10+.

When GPS is DISABLED you won'T see any casinos on those devices. All on the latest Droid 10

The screen above shows the debug output on versions 0.4.9

**Comment by danielwwf** [comment]
this seems to be fixed.
